name: Unit Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  unit-tests:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        node_version:
          - '>=18.0.0'
          - 'lts/*'
      fail-fast: false
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'
      - run: pnpm run test:coverage
      - name: SonarQube Scan
        if: matrix.os == 'ubuntu-latest'
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Codecov Scan
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/junit.xml,!./cache
          fail_ci_if_error: true
